FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src

COPY ["MapHub/MapHub.csproj", "./"]
RUN dotnet restore "MapHub.csproj"

COPY MapHub/ .
RUN dotnet publish "MapHub.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
ENV DOTNET_GCConserveMemory=9
EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MapHubApp.dll"]
