// <auto-generated />
using MapHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MapHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602000002_AddPlanDescAndDayNum")]
    partial class AddPlanDescAndDayNum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
